# Generated by Django 5.2.6 on 2025-09-24 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "site_name",
                    models.CharField(max_length=200, verbose_name="Nome do Site"),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("business", "Site Empresarial"),
                            ("portfolio", "Portfólio"),
                            ("blog", "Blog"),
                            ("ecommerce", "E-commerce"),
                            ("landing", "Landing Page"),
                        ],
                        default="business",
                        max_length=20,
                        verbose_name="Tipo de Site",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Palavras-chave (separadas por vírgula)",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=200, verbose_name="Nome da Empresa/Pessoa"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de Contato"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Endereço"),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "services",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Serviços/Produtos (um por linha)",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#0d6efd", max_length=7, verbose_name="Cor Primária"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="Cor Secundária"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Inter", max_length=100, verbose_name="Fonte"
                    ),
                ),
                (
                    "generated_html",
                    models.TextField(blank=True, null=True, verbose_name="HTML Gerado"),
                ),
                (
                    "generated_css",
                    models.TextField(blank=True, null=True, verbose_name="CSS Gerado"),
                ),
                (
                    "is_generated",
                    models.BooleanField(default=False, verbose_name="HTML Gerado"),
                ),
                (
                    "generation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Geração"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_info",
                        to="core.deployment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_infos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Informação do Site",
                "verbose_name_plural": "Informações dos Sites",
                "ordering": ["-created_at"],
            },
        ),
    ]
